[tool.black]
line-length = 120
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # Exclude these directories
  \.git
  | __pycache__
  | \.pytest_cache
  | \.github
  | venv
  | env
)/
'''
